### ISSUE TITLE
Minimum Ruby requirement?

### ISSUE THREAD

**Issue by praveendhawan** [Shopify/tree_stand#27]
I am getting the following error
```
SyntaxError (~/.rvm/gems/ruby-2.7.6/gems/tree_stand-0.2.0/lib/tree_stand/node.rb:170: syntax error, unexpected '=', expecting ';' or '\n')
```

Its related to this line 
```
def children = to_a
```

**Comment by DerekStride** [comment]
This is an endless ruby method introduced in ruby v3.0

https://rubyreferences.github.io/rubychanges/3.0.html#endless-method-definition
